server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    #db 연결 설정, 및 뷰리졸버 설정
spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/todolist?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: root
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true

mybatis:
  mapper-locations:
  - /mappers/*.xml